In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
data = pd.read_csv("iris.csv")

In [40]:
data.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0          51           7.0          3.2           4.7          1.4   
1          52           6.4          3.2           4.5          1.5   
2          53           6.9          3.1           4.9          1.5   
3          54           5.5          2.3           4.0          1.3   
4          55           6.5          2.8           4.6          1.5   

      Species  
0  versicolor  
1  versicolor  
2  versicolor  
3  versicolor  
4  versicolor

In [46]:
x = data.iloc[:,:4].values
y = data['Species'].values
x

array([[ 51. ,   7. ,   3.2,   4.7],
       [ 52. ,   6.4,   3.2,   4.5],
       [ 53. ,   6.9,   3.1,   4.9],
       [ 54. ,   5.5,   2.3,   4. ],
       [ 55. ,   6.5,   2.8,   4.6],
       [ 56. ,   5.7,   2.8,   4.5],
       [ 57. ,   6.3,   3.3,   4.7],
       [ 58. ,   4.9,   2.4,   3.3],
       [ 59. ,   6.6,   2.9,   4.6],
       [ 60. ,   5.2,   2.7,   3.9],
       [ 61. ,   5. ,   2. ,   3.5],
       [ 62. ,   5.9,   3. ,   4.2],
       [ 63. ,   6. ,   2.2,   4. ],
       [ 64. ,   6.1,   2.9,   4.7],
       [ 65. ,   5.6,   2.9,   3.6],
       [ 66. ,   6.7,   3.1,   4.4],
       [ 67. ,   5.6,   3. ,   4.5],
       [ 68. ,   5.8,   2.7,   4.1],
       [ 69. ,   6.2,   2.2,   4.5],
       [ 70. ,   5.6,   2.5,   3.9],
       [ 71. ,   5.9,   3.2,   4.8],
       [ 72. ,   6.1,   2.8,   4. ],
       [ 73. ,   6.3,   2.5,   4.9],
       [ 74. ,   6.1,   2.8,   4.7],
       [ 75. ,   6.4,   2.9,   4.3],
       [ 76. ,   6.6,   3. ,   4.4],
       [ 77. ,   6.8,   2.8,   4.8],
 

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33)

In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [51]:
from sklearn.naive_bayes import GaussianNB

In [52]:
classifier = GaussianNB()

In [53]:
classifier.fit(x_train,y_train)

GaussianNB()

In [54]:
y_pred = classifier.predict(x_test)
y_pred

array(['versicolor', 'virginica', 'virginica', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'virginica', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'virginica', 'virginica', 'virginica', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'versicolor'], dtype='<U10')

In [55]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[13  0]
 [ 0 20]]


In [56]:
from sklearn.metrics import accuracy_score
print("Accuracy : ",accuracy_score(y_test,y_pred))

Accuracy :  1.0


In [57]:
data = pd.DataFrame({'Real Value':y_test,'Predicted Value':y_pred})
data

Real Value Predicted Value
0   versicolor      versicolor
1    virginica       virginica
2    virginica       virginica
3   versicolor      versicolor
4    virginica       virginica
5    virginica       virginica
6   versicolor      versicolor
7   versicolor      versicolor
8   versicolor      versicolor
9    virginica       virginica
10   virginica       virginica
11   virginica       virginica
12   virginica       virginica
13  versicolor      versicolor
14   virginica       virginica
15  versicolor      versicolor
16   virginica       virginica
17   virginica       virginica
18   virginica       virginica
19   virginica       virginica
20  versicolor      versicolor
21   virginica       virginica
22  versicolor      versicolor
23  versicolor      versicolor
24   virginica       virginica
25   virginica       virginica
26   virginica       virginica
27   virginica       virginica
28   virginica       virginica
29  versicolor      versicolor
30  versicolor      versicolor
31   virginica       virginica
32  versicolor      versicolor

In [63]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.svm import SVC

In [64]:
iris = load_iris()

In [65]:
data = pd.DataFrame(iris.data,columns=iris.feature_names)

In [70]:
data['target'] = iris.target
data.sample(frac=0.01)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
82                 5.8               2.7                3.9               1.2   
116                6.5               3.0                5.5               1.8   

     target  
82        1  
116       2

In [74]:
targets = iris.target_names
print(targets)

['setosa' 'versicolor' 'virginica']


In [75]:
x = data.drop(['target'],axis=1).values
y = data['target'].values

In [76]:
cls = SVC()

In [77]:
cls.fit(x,y)

SVC()

In [79]:
x_pred = [[105,6.5,5,5.8]]
y_pred = cls.predict(x_pred)

print("Prediction :",format(target))

array([2])